server:
  port: 8080

spring:
  application:
    name: redis-test-app
  profiles:
    include:
      - yue-library-data-redis
    active:
      - dev

yue:
  redisson:
    singleServerConfig:
      address: 127.0.0.1:6379