#spring:
#  datasource:
#    druid:
#      url: jdbc:mysql://192.168.3.51:3310/yue_library_template_simple?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
##      url: jdbc:mysql://localhost:3306/yue_library_template_simple?characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

yue:
  crypto:
    aes-keyt: AES/ECB/PKCS5Padding3306
  redisson:
    singleServerConfig:
      address: 127.0.0.1:6379